### ISSUE TITLE
html里面的span会被翻译成block的view，从而导致了结构混乱

### ISSUE THREAD

**Issue by sheng-di** [Blubiubiu/wxParse#2]
![snipaste_2018-06-19_17-10-45](https://user-images.githubusercontent.com/13643746/41588230-c781f412-73e3-11e8-859a-1905d8ce5579.png)

**Comment by sheng-di** [comment]
问题已经找到了原因：原有的封装并没有引入样式。
解决办法：在**html2wxml.wpy**中的**style**里面添加：
`@import "../wxParse/wxParse.wxss";`

**Comment by Blubiubiu** [comment]
Thank u, i think it will help other people
