### ISSUE TITLE
引用后解析正常但是不展示解析后的富文本结构

### ISSUE THREAD

**Issue by YiXingYuFeng** [Blubiubiu/wxParse#4]

**Comment by YiXingYuFeng** [comment]
![image](https://user-images.githubusercontent.com/20083346/49636242-01814c00-fa3d-11e8-8e88-770163110bf2.png)

**Comment by Blubiubiu** [comment]
您能描述的信息多一些吗？我启动项目后并未发现您所说的问题，建议仔细查看demo

**Comment by YiXingYuFeng** [comment]
我事后找到问题的原因在于wepy要求的文件结构部分，单纯的引入此文件不管如何引入即使不报错，也不会显示富文本的内容，但是当文件放置于plugin文件夹下之后问题就解决了
 谢谢你
